// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LubricentroVelezV2.Models;

public partial class Aceites
{
    public int IdAceite { get; set; }

    public string Nombre { get; set; }

    public string Marca { get; set; }

    public virtual ICollection<OrdenesTrabajos> OrdenesTrabajos { get; set; } = new List<OrdenesTrabajos>();
}