// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LubricentroVelezV2.Models;

public partial class Autos
{
    public int IdAuto { get; set; }

    public string Patente { get; set; }

    public int? Año { get; set; }

    public string Vehiculo { get; set; }

    public int? IdPersona { get; set; }

    public virtual Personas IdPersonaNavigation { get; set; }

    public virtual ICollection<OrdenesTrabajos> OrdenesTrabajos { get; set; } = new List<OrdenesTrabajos>();
}