// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LubricentroVelezV2.Models;

public partial class Filtros
{
    public int IdFiltro { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<FiltrosXot> FiltrosXots { get; set; } = new List<FiltrosXot>();
}