// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LubricentroVelezV2.Models;

public partial class FiltrosXot
{
    public int IdFiltroXot { get; set; }

    public int? IdFiltro { get; set; }

    public int? IdOt { get; set; }

    public virtual Filtros IdFiltroNavigation { get; set; }

    public virtual OrdenesTrabajos IdOtNavigation { get; set; }
}