// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Configuration;
using Microsoft.EntityFrameworkCore;

namespace LubricentroVelezV2.Models;

public partial class OrdenesContext : DbContext
{
    public OrdenesContext()
    {
    }
    public OrdenesContext(DbContextOptions<OrdenesContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            optionsBuilder.UseSqlServer(connectionString);
        }
    }

    public virtual DbSet<Aceites> Aceites { get; set; }

    public virtual DbSet<Aditivos> Aditivos { get; set; }

    public virtual DbSet<Autos> Autos { get; set; }

    public virtual DbSet<Filtros> Filtros { get; set; }

    public virtual DbSet<FiltrosXot> FiltrosXots { get; set; }

    public virtual DbSet<OrdenesTrabajos> OrdenesTrabajos { get; set; }

    public virtual DbSet<Personas> Personas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aceites>(entity =>
        {
            entity.HasKey(e => e.IdAceite)
                .HasName("aaaaaAceites_PK")
                .IsClustered(false);

            entity.Property(e => e.Marca).HasMaxLength(50);
            entity.Property(e => e.Nombre).HasMaxLength(255);
        });

        modelBuilder.Entity<Aditivos>(entity =>
        {
            entity.HasKey(e => e.IdAditivo)
                .HasName("aaaaaAditivos_PK")
                .IsClustered(false);

            entity.Property(e => e.Nombre).HasMaxLength(255);
        });

        modelBuilder.Entity<Autos>(entity =>
        {
            entity.HasKey(e => e.IdAuto)
                .HasName("aaaaaAutos_PK")
                .IsClustered(false);

            entity.HasIndex(e => e.IdPersona, "AutosIdPersona");

            entity.HasIndex(e => e.IdPersona, "PersonasAutos");

            entity.Property(e => e.IdPersona).HasColumnName("idPersona");
            entity.Property(e => e.Patente).HasMaxLength(255);
            entity.Property(e => e.Vehiculo).HasMaxLength(255);

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.Autos)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("Autos_FK00");
        });

        modelBuilder.Entity<Filtros>(entity =>
        {
            entity.HasKey(e => e.IdFiltro)
                .HasName("aaaaaFiltros_PK")
                .IsClustered(false);

            entity.Property(e => e.Nombre).HasMaxLength(255);
        });

        modelBuilder.Entity<FiltrosXot>(entity =>
        {
            entity.HasKey(e => e.IdFiltroXot)
                .HasName("aaaaaFiltrosXOT_PK")
                .IsClustered(false);

            entity.ToTable("FiltrosXOT");

            entity.HasIndex(e => e.IdFiltro, "FiltrosFiltrosXOT");

            entity.HasIndex(e => e.IdFiltro, "IdFiltro");

            entity.HasIndex(e => e.IdOt, "IdOT");

            entity.HasIndex(e => e.IdOt, "OrdenesTrabajoFiltrosXOT");

            entity.Property(e => e.IdFiltroXot).HasColumnName("IdFiltroXOt");
            entity.Property(e => e.IdOt).HasColumnName("IdOT");

            entity.HasOne(d => d.IdFiltroNavigation).WithMany(p => p.FiltrosXots)
                .HasForeignKey(d => d.IdFiltro)
                .HasConstraintName("FiltrosXOT_FK00");

            entity.HasOne(d => d.IdOtNavigation).WithMany(p => p.FiltrosXots)
                .HasForeignKey(d => d.IdOt)
                .HasConstraintName("FiltrosXOT_FK01");
        });

        modelBuilder.Entity<OrdenesTrabajos>(entity =>
        {
            entity.HasKey(e => e.IdOt)
                .HasName("aaaaaOrdenesTrabajo_PK")
                .IsClustered(false);

            entity.ToTable("OrdenesTrabajo");

            entity.HasIndex(e => e.IdAceite, "AceitesOrdenesTrabajo");

            entity.HasIndex(e => e.IdAditivo, "AditivosOrdenesTrabajo");

            entity.HasIndex(e => e.IdAuto, "AutosOrdenesTrabajo");

            entity.HasIndex(e => e.IdAceite, "IdAceite");

            entity.HasIndex(e => e.IdAditivo, "IdAditivo");

            entity.HasIndex(e => e.IdAuto, "idAuto");

            entity.Property(e => e.Bateria).HasMaxLength(255);
            entity.Property(e => e.Caja).HasMaxLength(255);
            entity.Property(e => e.CajaTransferencia).HasMaxLength(255);
            entity.Property(e => e.DeleteLogico).HasColumnName("deleteLogico");
            entity.Property(e => e.DifDelantero).HasMaxLength(255);
            entity.Property(e => e.DifTrasero).HasMaxLength(255);
            entity.Property(e => e.Engrase).HasMaxLength(255);
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.FiltroAire).HasColumnName("FIltroAire");
            entity.Property(e => e.FluidoHidraulico).HasMaxLength(255);
            entity.Property(e => e.IdAuto).HasColumnName("idAuto");
            entity.Property(e => e.Limpiaparabrisas).HasMaxLength(255);
            entity.Property(e => e.LiquidoFreno).HasMaxLength(255);
            entity.Property(e => e.Observaciones).HasMaxLength(255);
            entity.Property(e => e.Radiador).HasMaxLength(255);
            entity.Property(e => e.UpsizeTs)
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("upsize_ts");

            entity.HasOne(d => d.IdAceiteNavigation).WithMany(p => p.OrdenesTrabajos)
                .HasForeignKey(d => d.IdAceite)
                .HasConstraintName("OrdenesTrabajo_FK00");

            entity.HasOne(d => d.IdAditivoNavigation).WithMany(p => p.OrdenesTrabajos)
                .HasForeignKey(d => d.IdAditivo)
                .HasConstraintName("OrdenesTrabajo_FK01");

            entity.HasOne(d => d.IdAutoNavigation).WithMany(p => p.OrdenesTrabajos)
                .HasForeignKey(d => d.IdAuto)
                .HasConstraintName("OrdenesTrabajo_FK02");
        });

        modelBuilder.Entity<Personas>(entity =>
        {
            entity.HasKey(e => e.IdPersona)
                .HasName("aaaaaPersonas_PK")
                .IsClustered(false);

            entity.Property(e => e.Nombre).HasMaxLength(255);
            entity.Property(e => e.Telefono).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}