// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LubricentroVelezV2.Models;

public partial class OrdenesTrabajos
{
    public int IdOt { get; set; }

    public DateTime? Fecha { get; set; }

    public double? Kilometraje { get; set; }

    public int? IdAceite { get; set; }

    public int? IdAuto { get; set; }

    public int? IdAditivo { get; set; }

    public bool? FiltroAceite { get; set; }

    public bool? FiltroAire { get; set; }

    public bool? FiltroCombustible { get; set; }

    public bool? FiltroAbitaculo { get; set; }

    public bool? FiltroHidraulico { get; set; }

    public bool? FiltroAireSecundario { get; set; }

    public bool? SecadorFrenos { get; set; }

    public bool? FiltroAgua { get; set; }

    public bool? TrampaAgua { get; set; }

    public string Caja { get; set; }

    public string DifTrasero { get; set; }

    public string DifDelantero { get; set; }

    public string CajaTransferencia { get; set; }

    public bool? AditivoCaja { get; set; }

    public bool? AditivoDifTrasero { get; set; }

    public bool? AditivoDifDelantero { get; set; }

    public bool? AditivoCajaTransferencia { get; set; }

    public string Engrase { get; set; }

    public int? Alemitas { get; set; }

    public string LiquidoFreno { get; set; }

    public string FluidoHidraulico { get; set; }

    public string Bateria { get; set; }

    public string Radiador { get; set; }

    public string Limpiaparabrisas { get; set; }

    public string Observaciones { get; set; }

    public byte[] UpsizeTs { get; set; }

    public bool DeleteLogico { get; set; }

    public virtual ICollection<FiltrosXot> FiltrosXots { get; set; } = new List<FiltrosXot>();

    public virtual Aceites IdAceiteNavigation { get; set; }

    public virtual Aditivos IdAditivoNavigation { get; set; }

    public virtual Autos IdAutoNavigation { get; set; }
}