// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LubricentroVelezV2.Models;

public partial class Personas
{
    public int IdPersona { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public virtual ICollection<Autos> Autos { get; set; } = new List<Autos>();
}